server:
  port: 8081 #访问端口
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dingcang?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: likaladi
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource #Druid连接池
    druid:
      initial-size: 1 #初始化连接数
      min-idle: 1 #最小空闲连接
      max-active: 20 #最大活动连接
      test-on-borrow: true #获取连接时测试是否可用
      stat-view-servlet:
        allow: true #监控页面启动
  application:
    name: user-service # 应用名称
mybatis:
  type-aliases-package: com.liwen.demo.pojo # mybatis 别名扫描
  mapper-locations: classpath:mappers/*.xml # mapper.xml文件位置,如果没有映射文件，请注释掉
eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
#    prefer-ip-address: true # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
#    ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找
    instance-id: ${spring.application.name}:${server.port} #注册服务的实例ID，唯一
    #服务续约：这两个值在生产环境不要修改，默认即可。（生产环境去掉，开发环境时间调小，方便查看）
    lease-expiration-duration-in-seconds: 10 #服务失效时间，默认值90秒，超时没发心跳，服务宕机，会从服务列表中移除
    lease-renewal-interval-in-seconds: 5 #服务续约(renew)的间隔，默认为30秒
logging:
  level:
    com:
      liwen: debug # 设置com.liwen包的日志级别为debug